columns:
  channel_name:
    caseSensitive: false
    dataType: 1
    generated: false
    name: CHANNEL_NAME
    nullable: false
    primaryKey: false
    unsigned: false
    visible: true
  host:
    caseSensitive: true
    dataType: 1
    generated: false
    name: HOST
    nullable: false
    primaryKey: false
    unsigned: false
    visible: true
  port:
    caseSensitive: false
    dataType: 4
    generated: false
    name: PORT
    nullable: false
    primaryKey: false
    unsigned: false
    visible: true
  user:
    caseSensitive: true
    dataType: 1
    generated: false
    name: USER
    nullable: false
    primaryKey: false
    unsigned: false
    visible: true
  network_interface:
    caseSensitive: true
    dataType: 1
    generated: false
    name: NETWORK_INTERFACE
    nullable: false
    primaryKey: false
    unsigned: false
    visible: true
  auto_position:
    caseSensitive: false
    dataType: 12
    generated: false
    name: AUTO_POSITION
    nullable: false
    primaryKey: false
    unsigned: false
    visible: true
  ssl_allowed:
    caseSensitive: false
    dataType: 12
    generated: false
    name: SSL_ALLOWED
    nullable: false
    primaryKey: false
    unsigned: false
    visible: true
  ssl_ca_file:
    caseSensitive: false
    dataType: 12
    generated: false
    name: SSL_CA_FILE
    nullable: false
    primaryKey: false
    unsigned: false
    visible: true
  ssl_ca_path:
    caseSensitive: false
    dataType: 12
    generated: false
    name: SSL_CA_PATH
    nullable: false
    primaryKey: false
    unsigned: false
    visible: true
  ssl_certificate:
    caseSensitive: false
    dataType: 12
    generated: false
    name: SSL_CERTIFICATE
    nullable: false
    primaryKey: false
    unsigned: false
    visible: true
  ssl_cipher:
    caseSensitive: false
    dataType: 12
    generated: false
    name: SSL_CIPHER
    nullable: false
    primaryKey: false
    unsigned: false
    visible: true
  ssl_key:
    caseSensitive: false
    dataType: 12
    generated: false
    name: SSL_KEY
    nullable: false
    primaryKey: false
    unsigned: false
    visible: true
  ssl_verify_server_certificate:
    caseSensitive: false
    dataType: 12
    generated: false
    name: SSL_VERIFY_SERVER_CERTIFICATE
    nullable: false
    primaryKey: false
    unsigned: false
    visible: true
  ssl_crl_file:
    caseSensitive: false
    dataType: 12
    generated: false
    name: SSL_CRL_FILE
    nullable: false
    primaryKey: false
    unsigned: false
    visible: true
  ssl_crl_path:
    caseSensitive: false
    dataType: 12
    generated: false
    name: SSL_CRL_PATH
    nullable: false
    primaryKey: false
    unsigned: false
    visible: true
  connection_retry_interval:
    caseSensitive: false
    dataType: 4
    generated: false
    name: CONNECTION_RETRY_INTERVAL
    nullable: false
    primaryKey: false
    unsigned: false
    visible: true
  connection_retry_count:
    caseSensitive: false
    dataType: 4
    generated: false
    name: CONNECTION_RETRY_COUNT
    nullable: false
    primaryKey: false
    unsigned: true
    visible: true
  heartbeat_interval:
    caseSensitive: false
    dataType: 8
    generated: false
    name: HEARTBEAT_INTERVAL
    nullable: false
    primaryKey: false
    unsigned: true
    visible: true
  tls_version:
    caseSensitive: false
    dataType: 12
    generated: false
    name: TLS_VERSION
    nullable: false
    primaryKey: false
    unsigned: false
    visible: true
name: replication_connection_configuration
