columns:
  channel_name:
    caseSensitive: false
    dataType: 1
    generated: false
    name: CHANNEL_NAME
    nullable: false
    primaryKey: false
    unsigned: false
    visible: true
  desired_delay:
    caseSensitive: false
    dataType: 4
    generated: false
    name: DESIRED_DELAY
    nullable: false
    primaryKey: false
    unsigned: false
    visible: true
name: replication_applier_configuration
