columns:
  key:
    caseSensitive: false
    dataType: 12
    generated: false
    name: KEY
    nullable: false
    primaryKey: false
    unsigned: false
    visible: true
  value:
    caseSensitive: false
    dataType: 12
    generated: false
    name: VALUE
    nullable: false
    primaryKey: false
    unsigned: false
    visible: true
name: INNODB_FT_CONFIG
