columns:
  specific_catalog:
    caseSensitive: false
    dataType: 12
    generated: false
    name: SPECIFIC_CATALOG
    nullable: false
    primaryKey: false
    unsigned: false
    visible: true
  specific_schema:
    caseSensitive: false
    dataType: 12
    generated: false
    name: SPECIFIC_SCHEMA
    nullable: false
    primaryKey: false
    unsigned: false
    visible: true
  specific_name:
    caseSensitive: false
    dataType: 12
    generated: false
    name: SPECIFIC_NAME
    nullable: false
    primaryKey: false
    unsigned: false
    visible: true
  ordinal_position:
    caseSensitive: false
    dataType: 4
    generated: false
    name: ORDINAL_POSITION
    nullable: false
    primaryKey: false
    unsigned: false
    visible: true
  parameter_mode:
    caseSensitive: false
    dataType: 12
    generated: false
    name: PARAMETER_MODE
    nullable: false
    primaryKey: false
    unsigned: false
    visible: true
  parameter_name:
    caseSensitive: false
    dataType: 12
    generated: false
    name: PARAMETER_NAME
    nullable: false
    primaryKey: false
    unsigned: false
    visible: true
  data_type:
    caseSensitive: false
    dataType: 12
    generated: false
    name: DATA_TYPE
    nullable: false
    primaryKey: false
    unsigned: false
    visible: true
  character_maximum_length:
    caseSensitive: false
    dataType: 4
    generated: false
    name: CHARACTER_MAXIMUM_LENGTH
    nullable: false
    primaryKey: false
    unsigned: false
    visible: true
  character_octet_length:
    caseSensitive: false
    dataType: 4
    generated: false
    name: CHARACTER_OCTET_LENGTH
    nullable: false
    primaryKey: false
    unsigned: false
    visible: true
  numeric_precision:
    caseSensitive: false
    dataType: 4
    generated: false
    name: NUMERIC_PRECISION
    nullable: false
    primaryKey: false
    unsigned: true
    visible: true
  numeric_scale:
    caseSensitive: false
    dataType: 4
    generated: false
    name: NUMERIC_SCALE
    nullable: false
    primaryKey: false
    unsigned: false
    visible: true
  datetime_precision:
    caseSensitive: false
    dataType: 4
    generated: false
    name: DATETIME_PRECISION
    nullable: false
    primaryKey: false
    unsigned: true
    visible: true
  character_set_name:
    caseSensitive: false
    dataType: 12
    generated: false
    name: CHARACTER_SET_NAME
    nullable: false
    primaryKey: false
    unsigned: false
    visible: true
  collation_name:
    caseSensitive: false
    dataType: 12
    generated: false
    name: COLLATION_NAME
    nullable: false
    primaryKey: false
    unsigned: false
    visible: true
  dtd_identifier:
    caseSensitive: false
    dataType: -1
    generated: false
    name: DTD_IDENTIFIER
    nullable: false
    primaryKey: false
    unsigned: false
    visible: true
  routine_type:
    caseSensitive: false
    dataType: 12
    generated: false
    name: ROUTINE_TYPE
    nullable: false
    primaryKey: false
    unsigned: false
    visible: true
name: PARAMETERS
